// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { backend } from '../models';

export function GetFileTree(arg1: string): Promise<Array<backend.FileItem>>;

export function GetLastOpened(): Promise<string>;

export function GetNewDirectoryFileTree(): Promise<Array<backend.FileItem>>;

export function Greet(arg1: string): Promise<string>;

export function ReadFile(arg1: string): Promise<string>;

export function SetLastOpened(arg1: string): Promise<void>;

export function WriteFile(arg1: string, arg2: string): Promise<void>;
