// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDirectory(arg1) {
  return window['go']['main']['App']['CreateDirectory'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function GetFileTree(arg1) {
  return window['go']['main']['App']['GetFileTree'](arg1);
}

export function GetFontSettings(arg1) {
  return window['go']['main']['App']['GetFontSettings'](arg1);
}

export function GetLastOpened() {
  return window['go']['main']['App']['GetLastOpened']();
}

export function GetNewDirectoryFileTree() {
  return window['go']['main']['App']['GetNewDirectoryFileTree']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadSession(arg1) {
  return window['go']['main']['App']['LoadSession'](arg1);
}

export function LoadTheorems(arg1) {
  return window['go']['main']['App']['LoadTheorems'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveFontSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveFontSettings'](arg1, arg2);
}

export function SaveSession(arg1, arg2) {
  return window['go']['main']['App']['SaveSession'](arg1, arg2);
}

export function SetLastOpened(arg1) {
  return window['go']['main']['App']['SetLastOpened'](arg1);
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2, arg3);
}
